version: '3'
services:
  remind:
    image: remind-registry.kr.ncr.ntruss.com/remind
    container_name: remind
    restart: always
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul


